DECLARE @PROMEDIO DECIMAL(18,2)

SET @PROMEDIO = 0.0

CREATE TABLE ALUMNOS
(
    IDS INT PRIMARY KEY IDENTITY(1, 1),
    LU INT,
    NOMBRES NVARCHAR(50),
    NOTAS DECIMAL(18,2)
)

INSERT INTO ALUMNOS(LU, NOMBRES, NOTAS)
VALUES(2342, 'Anibal', 45.00),
(2343, 'Camila', 85.50),
(2333, 'Cecilia', 60.60),
(2337, 'Nelson', 75.70),
(2589, 'José', 85.90),
(2902, 'Jose Manuel', 85.20)

SELECT @PROMEDIO=AVG(NOTAS) FROM ALUMNOS
PRINT @PROMEDIO

SELECT LU, NOMBRES, NOTAS
FROM ALUMNOS
WHERE NOTAS>@PROMEDIO
ORDER BY LU DESC

SELECT LU, NOMBRES, NOTAS
FROM ALUMNOS
WHERE SOUNDEX(NOMBRES) = SOUNDEX('jose');

SELECT TOP(1) LU, NOMBRES, NOTAS
FROM ALUMNOS
WHERE NOTAS>@PROMEDIO
ORDER BY NOTAS DESC

SELECT TOP(1) LU, NOMBRES, NOTAS
FROM ALUMNOS
WHERE NOTAS>@PROMEDIO
ORDER BY NOTAS ASC;

 
SELECT * FROM ALUMNOS